//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient1.CompanyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompanyPublicService")]
    public interface ICompanyPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyPublicService/GetPublicInfo", ReplyAction="http://tempuri.org/ICompanyPublicService/GetPublicInfoResponse")]
        string GetPublicInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyPublicService/GetPublicInfo", ReplyAction="http://tempuri.org/ICompanyPublicService/GetPublicInfoResponse")]
        System.Threading.Tasks.Task<string> GetPublicInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyPublicServiceChannel : WebClient1.CompanyService.ICompanyPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyPublicServiceClient : System.ServiceModel.ClientBase<WebClient1.CompanyService.ICompanyPublicService>, WebClient1.CompanyService.ICompanyPublicService {
        
        public CompanyPublicServiceClient() {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyPublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPublicInfo() {
            return base.Channel.GetPublicInfo();
        }
        
        public System.Threading.Tasks.Task<string> GetPublicInfoAsync() {
            return base.Channel.GetPublicInfoAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompanyConfidentialService")]
    public interface ICompanyConfidentialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyConfidentialService/GetConfidentialInfo", ReplyAction="http://tempuri.org/ICompanyConfidentialService/GetConfidentialInfoResponse")]
        string GetConfidentialInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyConfidentialService/GetConfidentialInfo", ReplyAction="http://tempuri.org/ICompanyConfidentialService/GetConfidentialInfoResponse")]
        System.Threading.Tasks.Task<string> GetConfidentialInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyConfidentialServiceChannel : WebClient1.CompanyService.ICompanyConfidentialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyConfidentialServiceClient : System.ServiceModel.ClientBase<WebClient1.CompanyService.ICompanyConfidentialService>, WebClient1.CompanyService.ICompanyConfidentialService {
        
        public CompanyConfidentialServiceClient() {
        }
        
        public CompanyConfidentialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyConfidentialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyConfidentialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyConfidentialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetConfidentialInfo() {
            return base.Channel.GetConfidentialInfo();
        }
        
        public System.Threading.Tasks.Task<string> GetConfidentialInfoAsync() {
            return base.Channel.GetConfidentialInfoAsync();
        }
    }
}
